apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  labels:
    app: whatsapp-mcp
type: Opaque
data:
  # Base64 encoded webhook secret (replace with your actual secret)
  # To generate: echo -n "your-webhook-secret" | base64
  WebHookSecretKey: eW91ci13ZWJob29rLXNlY3JldA==
